version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: metade
      POSTGRES_PASSWORD: metade2025
      POSTGRES_DB: lineage_db
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
