services:
  mysql:
    image: mysql:8
    container_name: da-10week-classicmodels
    restart: unless-stopped
    command:
      - --lower-case-table-names=1
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: classicmodels
    ports:
      - "3306:3306"
    volumes:
      - ../data_과제/sampledatabase/mysqlsampledatabase.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - classicmodels-data:/var/lib/mysql

volumes:
  classicmodels-data:
